#!/usr/bin/env python3
"""Embed one H5 renderer in the Android, iOS and Flutter runtime sources."""
import argparse
import re
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
root = Path(__file__).resolve().parents[2]
template = (root / 'shared/h5/renderer.js').read_text().strip()


def renderer(platform, prefix):
    return template.replace('__AAB_H5_STATE_KEY__', '__aab' + platform + 'H5TargetV1').replace(
        '__AAB_H5_ERROR_PREFIX__', prefix + '_h5_')


ios = renderer('IOS', 'ios')
outputs = {}
for relative in [
    'ios/ai-app-bridge-ios/Sources/AiAppBridgeIOS/IOSH5Bridge.swift',
    'flutter/ai_app_bridge_flutter/ios/ai_app_bridge_flutter/Sources/AiAppBridgeIOS/IOSH5Bridge.swift',
]:
    path = root / relative
    source = path.read_text()
    pattern = r'(    static let renderer = #"""\n)[\s\S]*?(\n    """#)'
    if len(re.findall(pattern, source)) != 1:
        raise SystemExit('Expected one renderer anchor in ' + relative)
    embedded = '\n'.join('    ' + line for line in ios.splitlines())
    outputs[path] = re.sub(pattern, lambda match: match.group(1) + embedded + match.group(2), source)

android = renderer('Android', 'android').replace('$', "${'$'}")
outputs[root / 'android/ai-app-bridge-android/src/main/kotlin/io/github/mobileaidev/aiappbridge/android/AndroidH5Renderer.kt'] = (
    '// Generated by shared/h5/generate.py. Edit shared/h5/renderer.js.\n'
    'package io.github.mobileaidev.aiappbridge.android\n\n'
    'internal object AndroidH5Renderer {\n'
    '    val source = """\n' + '\n'.join('        ' + line for line in android.splitlines())
    + '\n    """.trimIndent()\n}\n')

outputs[root / 'flutter/ai_app_bridge_flutter/lib/src/h5_renderer.dart'] = (
    '// Generated by shared/h5/generate.py. Edit shared/h5/renderer.js.\n'
    "part of '../ai_app_bridge_flutter.dart';\n\n"
    "const _flutterH5Renderer = r\"\"\"\n" + renderer('Flutter', 'flutter') + '\n\"\"\";\n')

for path, expected in outputs.items():
    if args.check:
        if not path.is_file() or path.read_text() != expected:
            raise SystemExit('Generated renderer differs: ' + str(path.relative_to(root)))
    else:
        path.write_text(expected)
print(('Checked' if args.check else 'Generated') + ' 4 platform renderer copies')
